# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'BetterSleep' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BetterSleep
  pod 'Firebase/Core'
  pod 'Firebase/Messaging', '~> 5.15.0'

  target 'BetterSleep-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BetterSleepTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BetterSleep-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BetterSleep-tvOS

  #target 'BetterSleep-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  #end

end
